<?php
# DATA SOURCE NAME

#MOTOR DE BASE DE DATOS 'DRIVER' DEBE IR EN MINÚSCULA
define('MOTOR_BD', 'mysql');

# IP SERVIDOR USADO PARA ACCEDER A LA BD
define("SERVIDOR_BD","localhost");

# PUERTO DEL SERVIDOR USADO PARA ACCEDER A LA BD
define('PUERTO_BD', '3306');


# NOMBRE DE USUARIO PARA ACCEDER A LA BD
define('USUARIO_BD', 'root');

# PASSWORD DEL
define('CLAVE_BD', '123456');

# EL NOMBRE DE LA BASE DE DATOS
define("NOMBRE_BD","q-sort");

#CHARSET
define("CHARSET","UTF8");
?>